#!/bin/bash
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
# Check Container Logs
# -------------------------------------------------------------------------------------------
ORG=$1
SERVICE=$2
if test "$#" -lt 1; then
	echo "Extracting ORG and Service Names..."
	# Get the Org Name and Container Name from Properties file
	cd ../../
	ORG=`getServiceName 1`
	SERVICE=`getServiceName 4`
	cd src/docker
fi
CID=`cat $SERVICE.cid`
echo "Checking logs for Container = $SERVICE and Container ID = $CID"
docker logs $CID
